--- Cargo.toml.orig	2026-01-07 07:34:20 UTC
+++ Cargo.toml
@@ -41,9 +41,7 @@ nix = { version = "0.30.1", default-feat
 ] }
 num-traits = "0.2.19"
 once_cell = "1.19.0"
-pcre2 = { git = "https://github.com/fish-shell/rust-pcre2", tag = "0.2.9-utf32", default-features = false, features = [
-    "utf32",
-] }
+pcre2 = { path = "../rust-pcre2-0.2.9-utf32", default-features = false, features = ["utf32"] }
 phf = { version = "0.13", default-features = false }
 phf_codegen = "0.13"
 portable-atomic = { version = "1", default-features = false, features = [
