--- cargo-crates/getrandom-0.1.13/Cargo.toml.orig	1970-01-01 00:00:00 UTC
+++ cargo-crates/getrandom-0.1.13/Cargo.toml
@@ -33,6 +33,9 @@ version = "1.0"
 optional = true
 package = "rustc-std-workspace-core"
 
+[dependencies.errno-dragonfly]
+version = "0.1.1"
+
 [dependencies.log]
 version = "0.4"
 optional = true
